// In-app legal + transparency content (REQ-PRIV-001/003). Three documents —
// Privacy Policy, Terms of Service, and an AI-use disclosure — rendered in a
// modal, plus a small links row used on both the signed-out and signed-in
// screens. Content is embedded (no markdown dependency) so it ships in the
// bundle and works offline.
//
// NOTE: these are honest, complete drafts written to the product's actual data
// flows, but they still need a lawyer's sign-off before public launch (OQ-02).
// Update LAST_UPDATED, the contact email, and the governing-law line for your
// entity before going live.

const LAST_UPDATED = "June 12, 2026";
const CONTACT_EMAIL = "support@wildcard.app"; // ← change to your real support address

export type LegalDocId = "privacy" | "terms" | "ai";

export function LegalLinks({ onOpen }: { onOpen: (doc: LegalDocId) => void }) {
  return (
    <span className="legal-links">
      <button onClick={() => onOpen("privacy")}>Privacy</button>
      <span aria-hidden>·</span>
      <button onClick={() => onOpen("terms")}>Terms</button>
      <span aria-hidden>·</span>
      <button onClick={() => onOpen("ai")}>AI&nbsp;use</button>
    </span>
  );
}

const TITLES: Record<LegalDocId, string> = {
  privacy: "Privacy Policy",
  terms: "Terms of Service",
  ai: "How Wild Card uses AI",
};

export function LegalModal({ doc, onClose }: { doc: LegalDocId; onClose: () => void }) {
  return (
    <div className="legal-overlay" onClick={onClose}>
      <div className="legal-modal" onClick={(e) => e.stopPropagation()}>
        <div className="legal-head">
          <h2>{TITLES[doc]}</h2>
          <button className="legal-close" onClick={onClose} aria-label="Close">
            ✕
          </button>
        </div>
        <div className="legal-body">
          <p className="legal-meta">Last updated: {LAST_UPDATED}</p>
          {doc === "privacy" && <Privacy />}
          {doc === "terms" && <Terms />}
          {doc === "ai" && <AiUse />}
        </div>
      </div>
    </div>
  );
}

function Privacy() {
  return (
    <>
      <p>
        This policy explains what Wild Card collects, why, and the choices you have. We
        try to collect as little as possible.
      </p>
      <h3>What we collect</h3>
      <ul>
        <li>
          <strong>Your email address</strong> — to create your account and send
          passwordless sign-in links.
        </li>
        <li>
          <strong>Tool prompts and generated code</strong> — the descriptions you submit
          are sent to our AI provider to generate a tool (see “How Wild Card uses AI”).
          We process them to build and validate your tool.
        </li>
        <li>
          <strong>Account metadata</strong> — your plan, number of tools built, and
          (for subscribers) billing identifiers from our payment processor.
        </li>
        <li>
          <strong>Operational logs</strong> — minimal request/usage records for rate
          limiting, abuse prevention, and cost control.
        </li>
      </ul>
      <h3>What stays on your device</h3>
      <p>
        Your generated tools and the data they save (via the tool runtime) are stored
        locally in your browser. They are not uploaded to us. Clearing your browser
        storage removes them.
      </p>
      <h3>Who we share with</h3>
      <ul>
        <li>
          <strong>AI provider</strong> — your prompts are sent to our model provider to
          generate tools.
        </li>
        <li>
          <strong>Payment processor (Stripe)</strong> — to process subscriptions. We
          never see or store full card details.
        </li>
        <li>
          <strong>Email provider</strong> — to deliver sign-in links.
        </li>
      </ul>
      <p>We do not sell your personal information.</p>
      <h3>Your choices</h3>
      <ul>
        <li>
          <strong>Export</strong> — download all your tools at any time from Account.
        </li>
        <li>
          <strong>Delete</strong> — delete your account and associated server-side data
          from Account. This cancels any active subscription.
        </li>
      </ul>
      <h3>Contact</h3>
      <p>
        Questions or data requests: <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>.
      </p>
    </>
  );
}

function Terms() {
  return (
    <>
      <p>
        By using Wild Card you agree to these terms. Please read them; they include
        important limitations.
      </p>
      <h3>The service</h3>
      <p>
        Wild Card turns a plain-language description into a small, self-contained tool
        that runs in a sandbox in your browser. Tools are generated by an AI model and
        may not always be correct — review what a tool does before relying on it.
      </p>
      <h3>Acceptable use</h3>
      <p>You agree not to use Wild Card to create or attempt to create anything that:</p>
      <ul>
        <li>is illegal, or facilitates harm, fraud, malware, or attacks on others;</li>
        <li>infringes others’ rights or violates their privacy;</li>
        <li>attempts to bypass the sandbox, rate limits, or safety controls.</li>
      </ul>
      <p>We may refuse or remove content and suspend accounts that violate these terms.</p>
      <h3>Your content</h3>
      <p>
        You own the tools you create. You are responsible for how you use them and for
        complying with applicable laws.
      </p>
      <h3>Plans and billing</h3>
      <p>
        A free tier includes a limited number of builds. Paid subscriptions are billed
        through our payment processor on a recurring basis until cancelled. You can manage
        or cancel your subscription at any time from Account.
      </p>
      <h3>No warranty; limitation of liability</h3>
      <p>
        The service and generated tools are provided “as is,” without warranties of any
        kind. To the maximum extent permitted by law, Wild Card is not liable for any
        indirect or consequential damages, or for outcomes arising from tools you generate
        or run.
      </p>
      <h3>Changes</h3>
      <p>
        We may update these terms; continued use after an update means you accept the
        revised terms.
      </p>
      <h3>Contact</h3>
      <p>
        <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>
      </p>
    </>
  );
}

function AiUse() {
  return (
    <>
      <p>
        Wild Card builds tools using a large language model. We want to be clear about
        what that means for you.
      </p>
      <h3>What gets sent to the AI</h3>
      <p>
        When you describe a tool (or ask to edit one), your description and — for edits —
        the current tool’s source are sent to our AI provider to generate the result. Your
        email and the data your tools save locally are <strong>not</strong> sent to the
        model.
      </p>
      <h3>AI output can be wrong</h3>
      <p>
        Generated tools are produced automatically and are not reviewed by a person. They
        can contain mistakes. The source is always viewable and editable so you can check
        and change what a tool does before relying on it.
      </p>
      <h3>Safety</h3>
      <p>
        We screen requests and refuse ones that appear intended to cause harm or break the
        law. Every tool is validated in a locked-down sandbox before it’s delivered, and
        tools cannot reach the network except through a small set of vetted data sources.
      </p>
      <h3>No background data access</h3>
      <p>
        Tools run in an isolated sandbox. They cannot read your other tools’ data, your
        files, or your device.
      </p>
    </>
  );
}
